version: '3'
services:
  server:
    image: nginx:1.21.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - "$HOME/www/iac-docker/nginx-webserver/nginx.conf:/etc/nginx/nginx.conf"
      - "$HOME/www/iac-docker/nginx-webserver/ssl:/etc/nginx/certs"
networks:
  default:
    external:
      name: alegria-digital_default
