version: '3'
services:
  api:
    image: viniciusks13/alegria-api:v4
    ports:
      - 8081:8081
  api-player:
    image: viniciusks13/alegria-audio-player-api:1.0
    ports:
      - 3000:3000
  # web-server:
  #   image: nginx:1.21.6
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - "$HOME/www/iac-docker/nginx-webserver/nginx.conf:/etc/nginx/nginx.conf"
  #     - "$HOME/www/iac-docker/nginx-webserver/ssl:/etc/nginx/certs"
